kind: pipeline
type: docker
name: build
steps:
  - name: push # 自动推送到私有仓库update
    image: plugins/docker
    pull: if-not-exists # 镜像拉取策略
    settings:
      registry: registry.xiaoyou.host # 私有仓库地址
      repo: registry.xiaoyou.host/xiaoyou66/index-front # 仓库全称
      use_cache: true
      username: docker # 设置私有仓库的账号密码
      password: docker
      tags: # 设置我们的标签
        - latest
        - 0.0.1

trigger:
  event: push
  branch:
    - main  # 仅监听 main 分支的推送
